### ISSUE TITLE
Where are the .azm download files are saved?

### ISSUE THREAD

**Issue by armughan03** [freewillfx-azenqos/azenqos_qgis_plugin#2]
Hi, 
I am trying to download multiple log files from AZENQOS plugin and it downloads perfectly for QGIS but where can I find these downloaded ones on My PC?

**Comment by ykasidit** [comment]
Hello, I think you are referring to online mode? it is merged on the server and sent as a single sqlite db file, it is saved to a temporary folder tmp_gen inside the plugin's folder inside the qgis data folder. You can save the db for further analysis with the 'save db' button (next to the open log button - kindly update your qgis plugin to latest release first).
